service: bot
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
  getInfoProduct:
    handler: handler.getInfoProduct
  getWeather:
    handler: handler.getWeather